In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('C:/Users/abhay.manhas/Downloads/Flavor_Rating.csv')

In [3]:
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3
9,Belgim Chocolate,Chocolate,No,5.2,8.2,11.1
10,Abc Chaoclate,Chocolate,No,9.0,7.8,10.0

In [4]:
df.groupby('Liked')[['Flavor Rating', 'Texture Rating', 'Total Rating']].mean()

       Flavor Rating  Texture Rating  Total Rating
Liked
No               5.0        5.880000      9.060000
Yes              8.1        7.033333     15.166667

In [5]:
df.groupby(['Base Flavor']).agg({'Flavor Rating':['mean','min','max'],'Texture Rating':['mean','min','max'],'Total Rating':['mean','min','max']})

            Flavor Rating            Texture Rating           Total Rating  \
                     mean  min   max           mean  min  max         mean
Base Flavor
Chocolate            7.88  5.2   9.0           7.54  7.0  8.2        13.64
Vanilla              5.70  2.3  10.0           5.65  3.4  8.0        11.35


              min   max
Base Flavor
Chocolate    10.0  16.6
Vanilla       5.7  18.0

In [6]:
df.groupby(['Base Flavor','Liked']).agg({'Flavor Rating':['mean','min','max']})

                  Flavor Rating
                           mean  min   max
Base Flavor Liked
Chocolate   No              7.1  5.2   9.0
            Yes             8.4  8.2   8.8
Vanilla     No              3.6  2.3   4.7
            Yes             7.8  6.5  10.0